version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12-buster

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - module_cache-{{ checksum "yarn.lock" }}
      - run:
          name: Check for dependencies
          command: "([[ -d node_modules ]] && circleci-agent step halt) || exit 0"
      - run:
          name: Install Packages
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: module_cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  check:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - module_cache-{{ checksum "yarn.lock" }}
      - run:
          name: TypeScript
          command: yarn run check
      - run:
          name: Unit Tests
          command: yarn run test --maxWorkers=2
      - run:
          name: ESLint
          command: yarn run lint

  build:
    executor: node
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - module_cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn run build

  staging_site:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - module_cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build Staging Site
          command: |
            cd packages/site
            yarn run build --staging
      - deploy:
          name: Deploy Staging Site
          command: |
            cd packages/site
            node scripts/deploy/surge.js

  production_site:
    executor: node
    steps:
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - checkout
      - restore_cache:
          keys:
            - module_cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build Production Site
          command: |
            cd packages/site
            yarn run build
      - deploy:
          name: Deploy Production Site
          command: |
            cd packages/site
            node scripts/deploy/aws.js

workflows:
  version: 2
  stable:
    jobs:
      - setup
      - check:
          requires:
            - setup
      - build:
          requires:
            - setup
      - staging_site:
          filters:
            branches:
              ignore: main
          requires:
            - setup
      - production_site:
          filters:
            branches:
              only: main
          requires:
            - setup
