notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

language: node_js
cache:
  yarn: true
node_js:
  - '10'

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: Build
      script:
        - yarn run build

    - stage: Lint and Check
      script:
        - yarn run lint

    - stage: Test
      script:
        - yarn run coverage
        - yarn run codecov
